### ISSUE TITLE
Getting Missing job id error

### ISSUE THREAD

**Issue by k-vishwa** [kgillan/Densify-K8s#2]
Hi, 
I'm seeing the below error when the Dockerfile java command runs

Client configuration will be picked up from: config
**** Densify Ingestion Client Framework (IngestionHttpClient v1.3.9e (JWT-enabled)) ****
Running default creation setup.
No jobs found.
401:
Re-run command with -v flag for extra information.
AUTOCREATE: Job creation failed...
401:
Re-run command with -v flag for extra information.
No jobs found.
401:
Re-run command with -v flag for extra information.
Running setup command.
Running command: [python] with argument list: [discover.py --file config/config.cfg]
Stand by...
Standard output of command:

Standard error output of command:

Looking for 0-return code...
SUCCESS
upload
Missing job id (-j parameter); use -l flag to find by name if required.

usage: <command> -o upload -j <job ID> [-f <file|directory>] [-e] [-t
                 <HH:MM>] [-m <modifier>] [-Z] [--help] [-d] [-v] [-S
                 <configurationPath>] [-l <job_name>] [-r] [-c]
                 [--username <Densify username>] [--password <plaintext
                 Densify password>] [--encryptedpw <encrypted Densify
                 password>]
 -c,--createjob                                  auto create job
 -C,--configdir <config directory name>          client config directory
 -d,--debug                                      emit debugging
                                                 information
 -e,--execute                                    triggers command
                                                 execution post-upload
 -f,--filespec <file/directory name>             file and/or directory
                                                 specification
 -h,--help                                       prints extended help
 -j,--job <job number>                           job ID
 -l,--locatejob <job name>                       job name to convert to ID
 -m,--modifier <modifier>                        execution modifier
 -o,--operation-type <operation>                 framework operation to
                                                 run
 -r,--runcommand                                 run setup command
 -S,--sourcedir <directory name>                 client working directory
 -t,--time <exec time>                           scheduled execution time
                                                 HH:MM
 -v,--verbose                                    verbose mode
 -x,--username <Densify user>                    username override
 -y,--password <Densify plaintext password>      password override
 -Z,--zip                                        zip before transmission
 -z,--encryptedpw <Densify encrypted password>   encrypted password
                                                 override

**Comment by kgillan** [comment]
Can you provide details on how you have configured the config.cfg file you are using in this test as it appears you may have some incorrect settings for the Densify server. If you do not want to share here due to confidentiality can you send a note through your Densify account contact.
